#!/bin/bash
#
# Copyright (c) 2014 Red Hat, Inc. All rights reserved.
#
# This copyrighted material is made available to anyone wishing
# to use, modify, copy, or redistribute it subject to the terms
# and conditions of the GNU General Public License version 2.
#
# This program is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public
# License along with this program; if not, write to the Free
# Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA 02110-1301, USA.

. <(acid-strict-env || echo exit 1)
. acid_repo.sh

declare -r PROGNAME=`basename "$0"`

# Output usage information.
function usage()
{
	cat <<EOF
Usage: $PROGNAME MASTER_GIT_DIR
Divert commits submitted to a git post-receive hook to CI.

Arguments:
    MASTER_GIT_DIR  Git directory pushing to which is being imitated.
EOF
}

if [ "$#" != 1 ]; then
    echo "$PROGNAME: Invalid number of arguments" >&2
    usage >&2
    exit 1
fi

declare master_git_dir
master_git_dir=`readlink -f "$1"`

# Check master git dir is a repository
git rev-parse --resolve-git-dir "$master_git_dir" >/dev/null

# Load repository
declare repo_str
repo_str=`acid_repo_load "$master_git_dir"` || {
    echo "Failed to load repository configuration" >&2
    exit 1
}

# Handle reference updates
while read -r rev_old rev_new ref; do
    acid_repo_ref_update "$repo_str" true "$rev_old" "$rev_new" "$ref"
done
