#!/bin/bash
#
# Output a Bash script setting installation-dependent environment variables
# for ACID - another CI dispatcher
#
# Copyright (c) 2014 Red Hat, Inc. All rights reserved.
#
# This copyrighted material is made available to anyone wishing
# to use, modify, copy, or redistribute it subject to the terms
# and conditions of the GNU General Public License version 2.
#
# This program is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public
# License along with this program; if not, write to the Free
# Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA 02110-1301, USA.

set -e
thud-env

cat <<"EOF"

if [ -z "${_ACID_LIB_SH+set}" ]; then
declare _ACID_LIB_SH=

declare -r ACID_LIB_PATH="../lib"  # Replaced on installation

if [ "${ACID_LIB_PATH::1}" == "/" ]; then
    ACID_LIB_DIR="$ACID_LIB_PATH"
else
EOF

printf '    ACID_LIB_DIR=`readlink -f %q/"$ACID_LIB_PATH"`\n' \
       "`dirname \"\$0\"`"

cat <<"EOF"
fi
declare -r ACID_LIB_DIR

PATH="$ACID_LIB_DIR:$PATH"

fi #_ACID_LIB_SH
EOF
