#!/bin/bash
#
# Update all local heads to match remote ones, triggering builds for every new
# commit.
#
# Copyright (c) 2014 Red Hat, Inc. All rights reserved.
#
# This copyrighted material is made available to anyone wishing
# to use, modify, copy, or redistribute it subject to the terms
# and conditions of the GNU General Public License version 2.
#
# This program is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public
# License along with this program; if not, write to the Free
# Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA 02110-1301, USA.

set -o nounset -o pipefail -o errexit

declare -r PROGNAME=`basename "$0"`
declare -r CONF_PFX="acid"

declare url_fmt
url_fmt=`git config --get "$CONF_PFX.public-url-fmt"` &&
        [ -n "$url_fmt" ] || {
    echo "$PROGNAME: Public build trigger URL format is not set" >&2
    exit 1
}

declare ref
declare branch
declare -a build_list
declare rev
declare build
declare url

while read -r ref; do
    branch="${ref#refs/heads/}"
    read -r -a build_list < <(
        git config --get "branch.$branch.$CONF_PFX-build-list"
    ) || true
    if [ "${#build_list[@]}" == 0 ]; then
        git update-ref "$ref" "$branch@{upstream}" >&2
    else
        while read -r rev; do
            for build in "${build_list[@]}"; do
                printf -v url "$url_fmt" "$branch" "$build" "$rev"
                wget --quiet -O/dev/null -- "$url" >&2
            done
            git update-ref "$ref" "$rev" >&2
        done < <(
            git rev-list --reverse "^$ref" "$branch@{upstream}"
        )
    fi
done < <(
    git for-each-ref --format='%(refname)' refs/heads
)
