#!/bin/bash
#
# Update all local heads to match remote ones, triggering builds for every new
# commit.
#
# Copyright (c) 2014 Red Hat, Inc. All rights reserved.
#
# This copyrighted material is made available to anyone wishing
# to use, modify, copy, or redistribute it subject to the terms
# and conditions of the GNU General Public License version 2.
#
# This program is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public
# License along with this program; if not, write to the Free
# Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA 02110-1301, USA.

. <(acid-strict-env || echo exit 1)
. acid_repo.sh

declare -r PROGNAME=`basename "$0"`
declare git_dir=${1-${GIT_DIR-.}}
git_dir=`readlink -f "$git_dir"`
GIT_DIR="$git_dir" git rev-parse --git-dir >/dev/null
declare repo_str
repo_str=`acid_repo_load "$git_dir"` || {
    echo "Failed to load repository configuration" >&2
    exit 1
}
acid_repo_branch_update_all "$repo_str"
